apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: skillbridge
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
